### ISSUE TITLE
Error at request PostProtoPayload

### ISSUE THREAD

**Issue by arjunvegda** [Ar1i/PokemonGo-Bot#2068]
After updating to the newest version

![image](https://cloud.githubusercontent.com/assets/14841132/17488630/31e26b96-5d68-11e6-8c5d-c2de080f5e48.png)

Another Instance 

![image](https://cloud.githubusercontent.com/assets/14841132/17488672/7660ee0a-5d68-11e6-8502-830e59edf89f.png)

It keeps on appearing

![image](https://cloud.githubusercontent.com/assets/14841132/17488766/d7c20a6c-5d68-11e6-8b31-9c68dbf9a523.png)

**Comment by Waiiim** [comment]
![image](https://cloud.githubusercontent.com/assets/20826690/17488875/a83aafa0-5d9b-11e6-90b8-977aabe5f518.png)

**Comment by NagaCS** [comment]
@Ar1i This is a legitimate issue, I'm experiencing it as well.

**Comment by Waiiim** [comment]
![capture d ecran 110](https://cloud.githubusercontent.com/assets/20826690/17488909/ce517476-5d9b-11e6-9244-ab1c512ad878.png)

**Comment by Ar1i** [comment]
fixing

**Comment by Ar1i** [comment]
should be fixed if not, open a new issue.

**Comment by J3azzo** [comment]
can you fix this restart every 30 min?

**Comment by qunzorez** [comment]
20:22:12] We can't find any PokeStops in a range of 55000m! 
[20:22:15] We can't find any PokeStops, which are unused! Probably the server ar 
e unstable, or you visted them all. Retrying..

**Comment by qunzorez** [comment]
http://s009.radikal.ru/i309/1608/c1/36cee7cbca65.png

**Comment by BittaBanter** [comment]
![bug](https://cloud.githubusercontent.com/assets/20910445/17490305/29e6b73a-5d9a-11e6-9f78-19a031cf0c0b.png)
And this is still happening. Keeps trying to catch the same pokemon but keeps missing.

**Comment by qunzorez** [comment]
It's softban, try unban

**Comment by BittaBanter** [comment]
![bug](https://cloud.githubusercontent.com/assets/20910445/17490352/61ed63f4-5d9a-11e6-9758-05ecc6a294f0.png)

And this, keeps trying to catch pokemon and keeps missing.

**Comment by owned85** [comment]
Same it is softban, try unban
