### ISSUE TITLE
Item Bug

### ISSUE THREAD

**Issue by harewei** [Ar1i/PokemonGo-Bot#3862]
Despite having setting items count, the bot is now ignoring the parameters and just throwing almost all my items away (my total item just went form 400 to 180 thanks to this bug...)

**Comment by harewei** [comment]
[08:58:59] ItemRazzBerry Qty: 45
[08:58:59] ItemPokeBall Qty: 25
[08:58:59] ItemGreatBall Qty: 61
[08:58:59] ItemUltraBall Qty: 108
[08:58:59] ItemPotion Qty: 0
[08:58:59] ItemSuperPotion Qty: 0
[08:58:59] ItemHyperPotion Qty: 31
[08:58:59] ItemMaxPotion Qty: 74
[08:58:59] ItemIncubatorBasicUnlimited Qty: 1
[08:58:59] ItemIncubatorBasic Qty: 0
[08:58:59] ItemRevive Qty: 22
[08:58:59] ItemLuckyEgg Qty: 2
[08:58:59] ItemIncenseOrdinary Qty: 4
[08:58:59] ItemTroyDisk Qty: 6
[08:58:59] Items: 379/400

[08:59:02] Recycled 25x ItemRazzBerry
[08:59:07] Recycled 41x ItemGreatBall
[08:59:10] Recycled 88x ItemUltraBall
[08:59:12] Recycled 11x ItemHyperPotion
[08:59:16] Recycled 54x ItemMaxPotion
[08:59:20] Recycled 2x ItemRevive

Even though my items.txt is
70
100
150
20
0
0
30
75
200
100
20

**Comment by Adj1e** [comment]
Same, me to

this is mine


[08:14:31] -----------------------[PLAYER STATS]-----------------------
[08:14:31] Level/EXP: 34 | 241,031/1,250,000 (19.28%)
[08:14:31] EXP to Level up: 1008969
[08:14:31] PokeStops visited: 26426
[08:14:31] KM Walked: 834.91
[08:14:31] Pokemon: 348 + 9 Eggs /400 (84 Evolvable)
[08:14:31] Pokedex Completion: 145/150 [96%]
[08:14:31] Stardust: 267,111
[08:14:31] ------------------------------------------------------------
[08:14:31] Pokemon Catch Count this session: 1
[08:14:31] PokeStop Farmed Count this session: 8
[08:14:31] ItemRazzBerry Qty: 24
[08:14:31] ItemPokeBall Qty: 104
[08:14:31] ItemGreatBall Qty: 17
[08:14:31] ItemUltraBall Qty: 10
[08:14:31] ItemPotion Qty: 21
[08:14:31] ItemSuperPotion Qty: 22
[08:14:31] ItemHyperPotion Qty: 21
[08:14:31] ItemMaxPotion Qty: 21
[08:14:31] ItemIncubatorBasicUnlimited Qty: 1
[08:14:31] ItemIncubatorBasic Qty: 0
[08:14:31] ItemRevive Qty: 21
[08:14:31] ItemMaxRevive Qty: 20
[08:14:31] ItemLuckyEgg Qty: 0
[08:14:31] ItemIncenseOrdinary Qty: 2
[08:14:31] ItemTroyDisk Qty: 9
[08:14:31] Items: 293/550
[08:14:31] ------------------------------------------------------------
[08:14:32] Recycled 4x ItemRazzBerry
[08:14:34] Recycled 4x ItemPokeBall
[08:14:38] Recycled 1x ItemPotion
[08:14:40] Recycled 2x ItemSuperPotion
[08:14:45] Recycled 1x ItemHyperPotion
[08:14:51] Recycled 1x ItemMaxPotion
[08:14:53] Recycled 1x ItemRevive


My setting 
ItemRazzBerry Qty: 50
ItemPokeBall Qty: 50	
ItemGreatBall Qty: 100
ItemUltraBall Qty: 100
ItemPotion Qty: 0	
ItemSuperPotion Qty: 0
ItemHyperPotion Qty: 100
ItemMaxPotion Qty: 350
ItemRevive Qty: 30
ItemMaxRevive Qty: 100

**Comment by vincent0817** [comment]
i having same problem with 2 player above
 please fix the bug above

1st i was thinking that maybe is my item setting wrong, i restart again the bot after  half an hour, still having same problem, it will automatic recycle all the great ball and ultra ball left 20 unit by starting bot, only pokeball will remain same unit with the setting only.


please fix this bug asap. thx

**Comment by s3if** [comment]
same problem here also!

**Comment by Adj1e** [comment]
@s3if  agree with you

**Comment by kiac20604** [comment]
same problem

**Comment by MTK4355** [comment]
Should be fixed in latest build. Please test and let me know.

**Comment by Adj1e** [comment]
@MTK4355 oke. work fine to me. But why you not set Masterball to zero? thanks for your awesome work.

**Comment by MTK4355** [comment]
Why would we set it to zero?

**Comment by k0ut4li4n0s** [comment]
@MTK4355 still not working it changes all my ball pot settings and recycling wrong :(

**Comment by MTK4355** [comment]
Delete existing configs and try it from scratch? Are you using German language? I need to add some logging to find out what is happening to you guys. standby for debug build update.

**Comment by Xelwon** [comment]
latest version  works well for me.
can you put a screenshot of the windows with maximun values at start, another with items tab and another with console windows recycling?

**Comment by Xelwon** [comment]
I need images of max potions and max revides. I haven`t got yet. :`(

**Comment by Xelwon** [comment]
problem found and solved into my fork for now.
https://github.com/Xelwon/PokemonGo-Bot/tree/master/Builds-Only
