### ISSUE TITLE
Microsoft .NET Framework Error

### ISSUE THREAD

**Issue by oltabaile** [Ar1i/PokemonGo-Bot#948]
This just started happening with the latest update.

![capture](https://cloud.githubusercontent.com/assets/20799016/17336706/5d58c082-58ad-11e6-8db6-6d372075426c.PNG)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: An exception occurred during a WebClient request. ---> System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at PokemonGo.RocketAPI.Console.GUI.GUI_Load(Object sender, EventArgs e) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Console\GUI.cs:line 86
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PokemonGo.RocketAPI.Console
    Assembly Version: 1.0.5.9
    Win32 Version: 1.0.5.9
    CodeBase: file:///C:/Users/501971512/Desktop/PokemonGo-Bot-master/Builds%20Only/Latest%20Build%20-%2002.08%2017.28/PokemonGo.RocketAPI.Console.exe
----------------------------------------
Pokemon Go Rocket API
    Assembly Version: 1.0.0.1
    Win32 Version: 1.0.0.1
    CodeBase: file:///C:/Users/501971512/Desktop/PokemonGo-Bot-master/Builds%20Only/Latest%20Build%20-%2002.08%2017.28/Pokemon%20Go%20Rocket%20API.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34285 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34294 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PokemonGo.RocketAPI.Logic
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/501971512/Desktop/PokemonGo-Bot-master/Builds%20Only/Latest%20Build%20-%2002.08%2017.28/PokemonGo.RocketAPI.Logic.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34283 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by hendek95** [comment]
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/ef0f1c39-fc92-4cde-9920-597a8d6981f9/403-error-the-remote-server-returned-an-error-403-forbidden?forum=sqlreportingservices i fixed here but now take memory error :(
just do it Go to: 'C:\WINDOWS\Microsoft.NET\Framework\V2.0.050727\Temporary ASP.NET Files'. (or where ever your .NET framework is installed on your machine)

Right click on the "Temporary ASP.NET Files" and select properties->secutity.

See if the "NETWORK SERVICE" is already part of the "User/Group" section. If not add it by typing "Network Service".
If it's already there then grant the write permissions.

**Comment by Ar1i** [comment]
http://pokemon-go.ar1i.xyz/lang/get.php what happens if you open it?

**Comment by hendek95** [comment]
tr.json spain.json ptBR.json ru.json france.json de.json

**Comment by Ar1i** [comment]
@oltabaile try to run it with admin?
@hendek95 thanks!

**Comment by oltabaile** [comment]
tr.json spain.json ptBR.json ru.json france.json de.json

I tried changing the permissions and running it as admin, still no luck.

**Comment by hendek95** [comment]
welcome. my link ll solve framework 403 error. but after solve 403 now "out of memory"

**Comment by Ar1i** [comment]
Out of memory is a problem from my side @hendek95 i am already trying to fix that

**Comment by Ar1i** [comment]
System.Net.WebException: An exception occurred during a WebClient request. ---> System.ArgumentException: Illegal characters in path.

can you give me the path where your bot is? @oltabaile

**Comment by oltabaile** [comment]
C:\Users\501971512\Desktop\PokemonGo-Bot-master\Builds Only\Latest Build - 02.08 17.28

**Comment by Ar1i** [comment]
Hmmm okay, i will try something..

**Comment by hendek95** [comment]
searching framework out of memory errors but couldn't find yet

**Comment by zyf911** [comment]
@oltabaile  the BOT works when I am at home now, my problem was related to network setting at work. Good luck to you~
